### 

# Test health

GET http://localhost:3002/health HTTP/1.1


### 

# Test signup

POST http://localhost:3002/auth/signup HTTP/1.1
Content-Type: application/json

{
  "username": "sample",
  "email": "sample@example.com",
  "password": "sample_password"
}


### 

# Test login
