// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "./src/orm/schema.prisma",
  migrations: {
    path: "./src/orm/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
