// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "@std/dotenv";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "./src/orm/schema.prisma",
  migrations: {
    path: "./src/orm/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
